import Header from "@/components/Header";
import ProtectedRouteProvider from "@/components/providers/ProtectedRouteProvider";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Provate Route",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <ProtectedRouteProvider>
            <body className="grid grid-cols-[250px_1fr] grid-rows-[4rem_auto] gap-4 h-screen">
                <Header />
                {children}
            </body>
        </ProtectedRouteProvider>
    );
}
